# Generated by Django 5.0 on 2023-12-06 20:03

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('nickname', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='birthday_reminder.group')),
            ],
        ),
    ]
